<?php
// docs/well_hdr_field_descriptions.php

return [
    'UWI' => 'Identificador Único de Pozo (Unique Well Identifier).',
    'WELL_NAME' => 'Nombre completo del pozo.',
    'SHORT_NAME' => 'Nombre corto o abreviado del pozo.',
    'PLOT_NAME' => 'Nombre del pozo para fines de ploteo o mapas.',
    'GOVT_ASSIGNED_NO' => 'Número asignado por el gobierno (posiblemente el pozo centinela).',
    'INITIAL_CLASS' => 'Clasificación Lahee inicial del pozo.',
    'CLASS' => 'Clasificación Lahee final del pozo.',
    'CURRENT_CLASS' => 'Clasificación actual del pozo.',
    'ORSTATUS' => 'Estado original del hoyo.',
    'CRSTATUS' => 'Estado actual del hoyo.',
    'COUNTRY' => 'País donde se ubica el pozo.',
    'GEOLOGIC_PROVINCE' => 'Cuenca o subcuenca geológica del pozo.',
    'PROV_ST' => 'Estado o provincia donde se ubica el pozo.',
    'COUNTY' => 'Municipio donde se ubica el pozo.',
    'FIELD' => 'Campo geológico al que pertenece el pozo.',
    'BLOCK_ID' => 'Identificador del bloque o parcela.',
    'LOCATION_TABLE' => 'Descripción de la ubicación del pozo.',
    'SPUD_DATE' => 'Fecha de mudanza del taladro (inicio de operaciones).',
    'FIN_DRILL' => 'Fecha de finalización de la perforación.',
    'RIGREL' => 'Fecha de suspensión del taladro.',
    'COMP_DATE' => 'Fecha de completación del pozo.',
    'ONINJECT' => 'Fecha de inicio como pozo inyector.',
    'ONPROD' => 'Fecha de inicio como pozo productor.',
    'DISCOVER_WELL' => 'Indica si es un pozo descubridor.',
    'DEVIATION_FLAG' => 'Indica si el pozo tiene desvío.',
    'PLOT_SYMBOL' => 'Símbolo utilizado para el pozo en mapas.',
    'WELL_HDR_TYPE' => 'Tipo de hoyo del pozo.',
    'WELL_NUMBER' => 'Número en la secuencia de perforación.',
    'PARENT_UWI' => 'UWI del hoyo principal (si es un hoyo secundario).',
    'TIE_IN_UWI' => 'UWI del hoyo precedente.',
    'PRIMARY_SOURCE' => 'Empresa de origen de los datos.',
    'CONTRACTOR' => 'Contratista de perforación.',
    'RIG_NO' => 'Código del taladro.',
    'RIG_NAME' => 'Nombre del taladro.',
    'HOLE_DIRECTION' => 'Dirección del hoyo.',
    'OPERATOR' => 'Empresa operadora del pozo.',
    'DISTRICT' => 'Distrito administrativo del pozo.',
    'AGENT' => 'Unidad de Explotación (UE) o Unidad de Producción (UP).',
    'LEASE_NO' => 'Código de licencia o convenio.',
    'LEASE_NAME' => 'Nombre de licencia o convenio.',
    'LICENSEE' => 'Licenciatario del pozo.',
    'DRILLERS_TD' => 'Profundidad total medida por el perforador.',
    'TVD' => 'Profundidad total verticalizada.',
    'LOG_TD' => 'Profundidad total de registro.',
    'LOG_TVD' => 'Profundidad total verticalizada de registro.',
    'PLUGBACK_TD' => 'Profundidad del tapón.',
    'WHIPSTOCK_DEPTH' => 'Profundidad K.O.P. (Kick-Off Point).',
    'WATER_DEPTH' => 'Profundidad de la capa de agua.',
    'ELEVATION_REF' => 'Referencia de elevación.',
    'ELEVATION' => 'Valor de elevación.',
    'GROUND_ELEVATION' => 'Elevación del terreno.',
    'FORM_AT_TD' => 'Última formación alcanzada en la profundidad total.'
];
?>
